"Execute skill seuqences generated by other scripts, e.g., random exploration."

import os
import sys
import argparse
import logging
import hydra
from omegaconf import DictConfig, OmegaConf
import argparse
sys.path.append(f".") # if you run this script from the root directory
sys.path.append("robotouille")
import robotouille
from robotouille.run_skill_sequence import exec_and_record
from src.utils import GPT4, load_from_file
from src.data_structure import Skill

@hydra.main(version_base=None, config_path="../robotouille/conf", config_name="test_config")
def main(cfg: DictConfig):
    if not cfg.evaluation.evaluate:
        kwargs = OmegaConf.to_container(cfg.game, resolve=True)
        environment_name = kwargs.pop('environment_name')
        # list all files under skill_sequence_fpath
        file_list = os.listdir(cfg.skill_sequence_dir)
        for f in file_list:
            f = os.path.join(cfg.skill_sequence_dir, f)
            skill_sequence = load_from_file(f)
            save_dir = "results/baselines/random_explore/burger/transitions/"
            run_burger(environment_name, skill_sequence, save_dir, **kwargs)

def run_burger(environment_name, skill_sequence, save_path, **kwcfg):
    "Take in skill sequence and execute them, save files to save_path"
    img_save_path = robotouille.run_skill_sequence.exec_and_record(environment_name, skill_sequence, save_path, **kwcfg)
    return img_save_path

if __name__ == "__main__":
    """
    Arguments & Default values:
    skill_sequence_dir
    """
    main()